### ISSUE TITLE
自监督辅助任务损失和推荐系统的监督学习任务的损失比例

### ISSUE THREAD

**Issue by XUPT-guoruihan** [wujcan/SGL#12]
您好！非常感谢您分享的代码  我注意到您在论文里说您的方法与图的模型无关  请问您做过自监督辅助任务损失  和  推荐系统的监督学习任务的损失  比例的相关实验研究吗？自监督辅助任务损失  和  推荐系统的监督学习任务的损失  在数值上以什么样的比例能取得较好的性能提升  或许您也可以提供一些参数优化的相关思路   期待您的回复！

**Comment by wujcan** [comment]
> 您好！非常感谢您分享的代码 我注意到您在论文里说您的方法与图的模型无关 请问您做过自监督辅助任务损失 和 推荐系统的监督学习任务的损失 比例的相关实验研究吗？自监督辅助任务损失 和 推荐系统的监督学习任务的损失 在数值上以什么样的比例能取得较好的性能提升 或许您也可以提供一些参数优化的相关思路 期待您的回复！

由于篇幅的限制，在最新的paper里我们把关于自监督任务比重的调参实验去掉了。但你可以在arXiv上找下早期版本的paper[https://arxiv.org/pdf/2010.10783v1.pdf]，里面有关于这一部分的实验

**Comment by XUPT-guoruihan** [comment]
感谢您的回复！祝工作顺利
