### ISSUE TITLE
自监督学习是否有助于防止过拟合

### ISSUE THREAD

**Issue by XUPT-guoruihan** [wujcan/SGL#13]
您好！非常感谢您分享的代码  我注意到您的代码中没有进行类似dropout的防止过拟合的操作   请问您是怎么防止过拟合现象产生的？  还是说  自监督学习本身就有防止模型过拟合的特性？  我想听听您的看法  期待您的回复！

**Comment by wujcan** [comment]
> 您好！非常感谢您分享的代码 我注意到您的代码中没有进行类似dropout的防止过拟合的操作 请问您是怎么防止过拟合现象产生的？ 还是说 自监督学习本身就有防止模型过拟合的特性？ 我想听听您的看法 期待您的回复！

自监督学习中构造subgraph就用到了dropout操作的；为了防止过拟合，我们也用了early stopping

**Comment by XUPT-guoruihan** [comment]
感谢您的回复！
