### ISSUE TITLE
RuntimeWarning: divide by zero encountered in power   d_inv = np.power(rowsum, -0.5).flatten()

### ISSUE THREAD

**Issue by OneSimplePerson** [wujcan/SGL#19]
Hello

I reported this error while running your code. Do I need to add a validation mechanism here, or is there a problem with my super-parameter adjustment? Hope to get your guidance, thank you!

**Comment by wujcan** [comment]
> 

It's a warning indicating that there are some nodes whose degree is zero, and we have added the following code to correct it:
d_inv[np.isinf(d_inv)] = 0.

So it's safe to run the code.

**Comment by OneSimplePerson** [comment]
I understand, thank you for your guidance!
