### ISSUE TITLE
conf error:'./conf/MF.properties' is empty!

### ISSUE THREAD

**Issue by wangyifeibeijing** [wujcan/SGL#6]
Hello, I have changed my root path ,but another error occurred.

This is it:

Traceback (most recent call last):
  File "/(#my root path#)/SGL/main.py", line 22, in <module>
    conf = Configurator(root_folder + "NeuRec.properties", default_section="hyperparameters")
  File "/(#my root path#)/SGL/util/configurator.py", line 68, in __init__
    self.alg_arg = self._read_config_file(arg_file)
  File "/(#my root path#)/SGL/util/configurator.py", line 88, in _read_config_file
    raise ValueError("'%s' is empty!" % filename)
ValueError: './conf/MF.properties' is empty!

**Comment by wujcan** [comment]
> Hello, I have changed my root path ,but another error occurred.
> 
> This is it:
> 
> Traceback (most recent call last):
> File "/(#my root path#)/SGL/main.py", line 22, in
> conf = Configurator(root_folder + "NeuRec.properties", default_section="hyperparameters")
> File "/(#my root path#)/SGL/util/configurator.py", line 68, in **init**
> self.alg_arg = self._read_config_file(arg_file)
> File "/(#my root path#)/SGL/util/configurator.py", line 88, in _read_config_file
> raise ValueError("'%s' is empty!" % filename)
> ValueError: './conf/MF.properties' is empty!

This is because you didn't specify the recommender model to SGL. You can set recommender=SGL in './NeuRec.properties', or run with the following command: python main.py --recommender=SGL

**Comment by wangyifeibeijing** [comment]
> This is because you didn't specify the recommender model to SGL. You can set recommender=SGL in './NeuRec.properties', or run with the following command: python main.py --recommender=SGL

cool，that's brilliant. thank you
