### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by BOTAKKK** [wujcan/SGL#9]
首先感谢您的代码，然后亚马逊数据集中的amazon-book.train中的user字段和item字段代表的是交互过的意思么？那么为什么amazon-book.train中的user，item是连续的，而amazon-book.test中的user，item是不连续的以及这字段的实际意义代表的是交互过的意思么？谢谢

**Comment by wujcan** [comment]
> 首先感谢您的代码，然后亚马逊数据集中的amazon-book.train中的user字段和item字段代表的是交互过的意思么？那么为什么amazon-book.train中的user，item是连续的，而amazon-book.test中的user，item是不连续的以及这字段的实际意义代表的是交互过的意思么？谢谢

数据集中的每一行代表一次观测到的交互记录，两个字段分布表示user ID和item ID，但这里的ID是经过map的

**Comment by BOTAKKK** [comment]
谢谢，不过还想问一个问题，经过map是什么意思呢？看了map阶段的代码，这段代码的意义是什么呢？生成的amazon-book_given_u0_i0.user2id 以及amazon-book_given_u0_i0.item2id  看起来都是一一对应的 而且都是相同的值

**Comment by wujcan** [comment]
> 谢谢，不过还想问一个问题，经过map是什么意思呢？看了map阶段的代码，这段代码的意义是什么呢？生成的amazon-book_given_u0_i0.user2id 以及amazon-book_given_u0_i0.item2id 看起来都是一一对应的 而且都是相同的值

原始数据集里的ID字段比较复杂，所以做了映射，从0开始计数，方便索引embedding table。这里给的数据就是经过映射后的，所以生成的XXX_given_u0_i0.XXX2id看起来是一一对应的

**Comment by BOTAKKK** [comment]
谢谢您
